name: Check CloudFront

on:
  workflow_dispatch:

permissions:
  id-token: write
  contents: read

jobs:
  check_cloudfront:
    name: Check CloudFront Configuration
    runs-on: ubuntu-latest

    steps:
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          role-to-assume: ${{ secrets.AWS_ROLE_ARN }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Get CloudFront Distribution Info
        run: |
          echo "Getting CloudFront distribution info..."
          aws cloudfront get-distribution --id ${{ secrets.CLOUDFRONT_DISTRIBUTION_ID }}

      - name: Check CloudFront Origin
        run: |
          echo "Checking CloudFront origin..."
          aws cloudfront get-distribution-config --id ${{ secrets.CLOUDFRONT_DISTRIBUTION_ID }}

      - name: Invalidate CloudFront Cache
        run: |
          echo "Invalidating CloudFront cache..."
          aws cloudfront create-invalidation --distribution-id ${{ secrets.CLOUDFRONT_DISTRIBUTION_ID }} --paths "/*"