name: Update Bucket Policy

on:
  workflow_dispatch:

permissions:
  id-token: write
  contents: read

jobs:
  update_policy:
    name: Update S3 Bucket Policy
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repo
        uses: actions/checkout@v3

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          role-to-assume: ${{ secrets.AWS_ROLE_ARN }}
          aws-region: eu-west-1

      - name: Update S3 Bucket Policy
        run: |
          echo "Updating S3 bucket policy..."
          aws s3api put-bucket-policy --bucket ${{ secrets.S3_BUCKET_NAME }} --policy file://updated-bucket-policy.json

      - name: Verify S3 Bucket Policy
        run: |
          echo "Verifying S3 bucket policy..."
          aws s3api get-bucket-policy --bucket ${{ secrets.S3_BUCKET_NAME }} --output json

      - name: Invalidate CloudFront Cache
        run: |
          echo "Invalidating CloudFront cache..."
          aws cloudfront create-invalidation --distribution-id ${{ secrets.CLOUDFRONT_DISTRIBUTION_ID }} --paths "/*"